export enum Roles {
	ADMIN = "ROLE_ADMIN",
	USER = "ROLE_STUDENT",
	FACULTY_COORDINATOR ="ROLE_FACULTY_COORDINATOR",
	CONTRACT_COORDINATOR = "ROLE_CONTRACT_COORDINATOR",
	DEAN_OFFICE_WORKER = "ROLE_DEAN_OFFICE_WORKER",
	FOREIGN_COUNTRIES_DEPARTMENT_REP = "ROLE_FOREIGN_COUNTRIES_DEPARTMENT_REP",
	OTHER_ADMIN = "ROLE_OTHER_ADMIN"

}

export interface LoginResponse {
	readonly token: string;
	readonly email: string;
	readonly roles: ReadonlyArray<string>;
}
