# Use rootuser/rootpass as user/password credentials

version: "3.8"
services:
    mongodb:
        image: mongo:5.0.6
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=rootuser
            - MONGO_INITDB_ROOT_PASSWORD=rootpass
    mongo-express:
        image: mongo-express:0.54.0
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
            - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_URL=mongodb://rootuser:rootpass@mongo:27017/
volumes:
    mongo-data:
        driver: local

networks:
    default:
        name: "mongodb-network"
